apiVersion: istio.banzaicloud.io/v1beta1
kind: Istio
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: istio
  namespace: istio-system
spec:
  version: "1.1.1"
  mtls: true
  includeIPRanges: "*"
  excludeIPRanges: ""
  autoInjectionNamespaces:
  - "default"
  controlPlaneSecurityEnabled: false
  sds:
    enabled: false
  pilot:
    enabled: true
    image: "docker.io/istio/pilot:1.1.1"
    replicaCount: 1
    minReplicas: 1
    maxReplicas: 5
    traceSampling: 1.0
  citadel:
    enabled: true
    image: "docker.io/istio/citadel:1.1.1"
    replicaCount: 1
  galley:
    enabled: true
    image: "docker.io/istio/galley:1.1.1"
    replicaCount: 1
  gateways:
    enabled: true
    ingress:
      enabled: true
      replicaCount: 1
      minReplicas: 1
      maxReplicas: 5
      serviceType: "LoadBalancer"
      serviceAnnotations: {}
      serviceLabels: {}
    egress:
      enabled: true
      replicaCount: 1
      minReplicas: 1
      maxReplicas: 5
      serviceType: "ClusterIP"
      serviceAnnotations: {}
      serviceLabels: {}
    k8singress:
      enabled: false
  mixer:
    enabled: true
    image: "docker.io/istio/mixer:1.1.1"
    replicaCount: 1
    minReplicas: 1
    maxReplicas: 5
  sidecarInjector:
    enabled: true
    image: "docker.io/istio/sidecar_injector:1.1.1"
    replicaCount: 1
    rewriteAppHTTPProbe: true
  nodeAgent:
    enabled: false
    image: "docker.io/istio/node-agent-k8s:1.1.1"
  proxy:
    image: "docker.io/istio/proxyv2:1.1.1"
    enableCoreDump: false
  proxyInit:
    image: "docker.io/istio/proxy_init:1.1.1"
  defaultPodDisruptionBudget:
    enabled: true
  outboundTrafficPolicy:
    mode: ALLOW_ANY
  tracing:
    enabled: true
    zipkin:
      address: zipkin.istio-system:9411
